### ISSUE TITLE
[FE] View categories

### ISSUE THREAD

**Issue by iamabeljoshua** [Stephen-Vincent/expenseTrackerProject#11]
As a user of the expense tracker app, I want to be able to see all my categories so I can delete any category I no longer need. 

We need to provide a page for the user to see all their categories, along with the color associated with the category. 

**A/C**

- Provide a UI area or a page for listing all the categories
- Each category has an action delete beside it, for deleting the category. 
- Fetch the categories from the BE and render on the page.

**Comment by Stephen-Vincent** [comment]
This is now visible in the category dropdown. The user will have the ability to delete a category from there. The categories that have expenses associated with them will be rendered as a key for the pie chart below. All expenses for the selected time period will be shown in a table below the pie chart, the user can delete and update each expense using the buttons. I will mark this as completed.
