### ISSUE TITLE
[FE] Delete categories

### ISSUE THREAD

**Issue by iamabeljoshua** [Stephen-Vincent/expenseTrackerProject#13]
As a user of the expense tracker app, I want to be able to delete categories so I can clean up any category I no longer need. 

**A/C**

- From the list of categories, a user may choose to delete a specific category
- When delete action is clicked, show a confirmation dialog prompting for confirmation
- Upon confirmation, send a request to the BE to delete the category
- On success, show a success toast, on error, show an error toast. 
- Refresh the category data so that an updated version is shown on the FE.

**Comment by Stephen-Vincent** [comment]
I have completed this task.
