### ISSUE TITLE
[FE] Add category

### ISSUE THREAD

**Issue by iamabeljoshua** [Stephen-Vincent/expenseTrackerProject#15]
As a user of the expense tracker app, I want to be able to add new categories to group my expenses

We need to provide a page for the user to add new categories

**A/C**

- Provide a UI area or a page for adding a category
- Call the BE to save the category
- Refresh the categories on the FE so we can show the updated version on the app.

**Comment by Stephen-Vincent** [comment]
Built the UI and posted references to the team on slack, still working on BE integration.
