### ISSUE TITLE
[FE] UI improvements 

### ISSUE THREAD

**Issue by iamabeljoshua** [Stephen-Vincent/expenseTrackerProject#3]
We need to make some UI improvements to the existing implementation such that the app looks tidy and professional. 

**A/C**

- Disable the buttons while submitting, this should be done for all pages: login, register, etc. 
- Show a loading indicator / change the label of the button while submitting. 
- Show a loading indicator on the dashboard page while loading the expense data.

**Comment by Stephen-Vincent** [comment]
I have completed this and there is now loading states for the buttons and charts. If you all would like to try this out you can simulate a slower network speed by changing the throttling to 'slow 3G' in the dev tools of your browser. I will mark this as completed.
