### ISSUE TITLE
[FE] Edit expense

### ISSUE THREAD

**Issue by iamabeljoshua** [Stephen-Vincent/expenseTrackerProject#7]
As a user of the expense tracker app, I should be able to edit an existing expense record so that I can correct any mistakes. 

At the moment, when an expense is recorded, it cannot be edited, we need to implement a support for editing expense records. 

**A/C**

- From the list of expenses displayed on the `ExpenseOverview` component, a user may select to edit any of the records. 
- When the edit is clicked, a modal appears, allowing the user to edit the description and or amount of the expense.  
   -  Call the `PATCH /expenses/:id` endpoint to edit an expense record. 
- Refresh the expenses to show an updated version. 
- On success, show a success toast, on error show an error toast.

**Comment by Stephen-Vincent** [comment]
Completed.
